DROP TABLE IF EXISTS comments;

CREATE TABLE IF NOT EXISTS users (
  id TEXT PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT,
  auth_provider_id TEXT,
  role TEXT NOT NULL DEFAULT 'admin',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS artists (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  bio TEXT NOT NULL,
  image_url TEXT NOT NULL,
  genre TEXT NOT NULL,
  city TEXT NOT NULL DEFAULT 'Houston',
  neighborhood TEXT NOT NULL,
  social_links TEXT NOT NULL DEFAULT '{}',
  streaming_links TEXT NOT NULL DEFAULT '{}',
  is_mainstream INTEGER NOT NULL DEFAULT 0,
  is_approved INTEGER NOT NULL DEFAULT 0,
  editorial_score INTEGER NOT NULL DEFAULT 0,
  local_relevance_score INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_artists_slug ON artists(slug);
CREATE INDEX IF NOT EXISTS idx_artists_approved ON artists(is_approved, is_mainstream);

CREATE TABLE IF NOT EXISTS songs (
  id TEXT PRIMARY KEY,
  artist_id TEXT NOT NULL REFERENCES artists(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  audio_url TEXT,
  downloadable_file_url TEXT,
  cover_art_url TEXT,
  is_download_enabled INTEGER NOT NULL DEFAULT 0,
  download_count INTEGER NOT NULL DEFAULT 0,
  stream_count INTEGER NOT NULL DEFAULT 0,
  unique_listener_count INTEGER NOT NULL DEFAULT 0,
  external_click_count INTEGER NOT NULL DEFAULT 0,
  submitted_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  approved_at TEXT,
  is_approved INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_songs_slug ON songs(slug);
CREATE INDEX IF NOT EXISTS idx_songs_artist ON songs(artist_id);
CREATE INDEX IF NOT EXISTS idx_songs_approved ON songs(is_approved);

CREATE TABLE IF NOT EXISTS chart_entries (
  id TEXT PRIMARY KEY,
  artist_id TEXT NOT NULL REFERENCES artists(id) ON DELETE CASCADE,
  rank INTEGER NOT NULL,
  previous_rank INTEGER,
  movement TEXT NOT NULL DEFAULT 'new',
  score REAL NOT NULL,
  week_start_date TEXT NOT NULL,
  week_end_date TEXT NOT NULL,
  is_manual_override INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_chart_week ON chart_entries(week_start_date, week_end_date, rank);
CREATE INDEX IF NOT EXISTS idx_chart_artist_week ON chart_entries(artist_id, week_start_date);

CREATE TABLE IF NOT EXISTS submissions (
  id TEXT PRIMARY KEY,
  artist_name TEXT NOT NULL,
  contact_email TEXT NOT NULL,
  song_title TEXT NOT NULL,
  genre TEXT NOT NULL,
  neighborhood TEXT NOT NULL,
  bio TEXT NOT NULL,
  social_links TEXT NOT NULL DEFAULT '{}',
  streaming_links TEXT NOT NULL DEFAULT '{}',
  audio_file TEXT,
  cover_art TEXT,
  permission_to_stream INTEGER NOT NULL DEFAULT 0,
  permission_to_download INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'pending',
  admin_notes TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_submissions_status ON submissions(status, created_at);

CREATE TABLE IF NOT EXISTS rss_sources (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  url TEXT NOT NULL UNIQUE,
  category TEXT NOT NULL,
  is_active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rss_items (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  source TEXT NOT NULL,
  link TEXT NOT NULL UNIQUE,
  description TEXT,
  image_url TEXT,
  published_at TEXT NOT NULL,
  category TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_rss_published ON rss_items(published_at DESC);
CREATE INDEX IF NOT EXISTS idx_rss_category ON rss_items(category, published_at DESC);

CREATE TABLE IF NOT EXISTS stream_logs (
  id TEXT PRIMARY KEY,
  song_id TEXT NOT NULL REFERENCES songs(id) ON DELETE CASCADE,
  artist_id TEXT NOT NULL REFERENCES artists(id) ON DELETE CASCADE,
  session_id TEXT NOT NULL,
  ip_hash TEXT NOT NULL,
  user_agent_hash TEXT NOT NULL,
  listened_seconds INTEGER NOT NULL DEFAULT 0,
  counted INTEGER NOT NULL DEFAULT 0,
  is_suspicious INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_stream_logs_song_artist ON stream_logs(song_id, artist_id, created_at);
CREATE INDEX IF NOT EXISTS idx_stream_logs_session ON stream_logs(song_id, session_id, created_at);

CREATE TABLE IF NOT EXISTS download_logs (
  id TEXT PRIMARY KEY,
  song_id TEXT NOT NULL REFERENCES songs(id) ON DELETE CASCADE,
  artist_id TEXT NOT NULL REFERENCES artists(id) ON DELETE CASCADE,
  session_id TEXT NOT NULL,
  ip_hash TEXT NOT NULL,
  user_agent_hash TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_download_logs_song_artist ON download_logs(song_id, artist_id, created_at);

CREATE TABLE IF NOT EXISTS external_click_logs (
  id TEXT PRIMARY KEY,
  artist_id TEXT NOT NULL REFERENCES artists(id) ON DELETE CASCADE,
  song_id TEXT REFERENCES songs(id) ON DELETE SET NULL,
  platform TEXT NOT NULL,
  url TEXT NOT NULL,
  session_id TEXT NOT NULL,
  ip_hash TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_external_click_logs_platform ON external_click_logs(platform, created_at);
CREATE INDEX IF NOT EXISTS idx_external_click_logs_artist ON external_click_logs(artist_id, created_at);
INSERT OR IGNORE INTO artists (id,name,slug,bio,image_url,genre,city,neighborhood,social_links,streaming_links,is_approved,editorial_score,local_relevance_score) VALUES ('artist-01','Bayou Neon','bayou-neon','A fictional Houston underground act channeling Third Ward block energy, DIY studio texture, and late-night Gulf Coast melodies.','https://placehold.co/640x640/111827/f97316?text=BA','Alt-R&B','Houston','Third Ward','{"instagram": "https://instagram.com/bayou-neon", "tiktok": "https://tiktok.com/@bayou-neon", "website": "https://example.com/bayou-neon"}','{"spotify": "https://open.spotify.com/search/bayou-neon", "youtube": "https://youtube.com/results?search_query=bayou-neon", "soundcloud": "https://soundcloud.com/bayou-neon", "bandcamp": "https://bayou-neon.bandcamp.com"}',1,9,9);
INSERT OR IGNORE INTO songs (id,artist_id,title,slug,audio_url,downloadable_file_url,cover_art_url,is_download_enabled,download_count,stream_count,unique_listener_count,external_click_count,approved_at,is_approved) VALUES ('song-01','artist-01','Third Ward After Midnight','bayou-neon-third-ward-after-midnight','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3','https://placehold.co/640x640/0f172a/22d3ee?text=HI30',1,256,1469,802,493,CURRENT_TIMESTAMP,1);
INSERT OR IGNORE INTO chart_entries (id,artist_id,rank,previous_rank,movement,score,week_start_date,week_end_date,is_manual_override) VALUES ('chart-01','artist-01',1,1,'same',7609,date('now','weekday 1','-7 days'),date('now','weekday 0'),0);
INSERT OR IGNORE INTO artists (id,name,slug,bio,image_url,genre,city,neighborhood,social_links,streaming_links,is_approved,editorial_score,local_relevance_score) VALUES ('artist-02','Velvet Silo','velvet-silo','A fictional Houston underground act channeling Heights block energy, DIY studio texture, and late-night Gulf Coast melodies.','https://placehold.co/640x640/111827/f97316?text=VE','Indie Rock','Houston','Heights','{"instagram": "https://instagram.com/velvet-silo", "tiktok": "https://tiktok.com/@velvet-silo", "website": "https://example.com/velvet-silo"}','{"spotify": "https://open.spotify.com/search/velvet-silo", "youtube": "https://youtube.com/results?search_query=velvet-silo", "soundcloud": "https://soundcloud.com/velvet-silo", "bandcamp": "https://velvet-silo.bandcamp.com"}',1,8,8);
INSERT OR IGNORE INTO songs (id,artist_id,title,slug,audio_url,downloadable_file_url,cover_art_url,is_download_enabled,download_count,stream_count,unique_listener_count,external_click_count,approved_at,is_approved) VALUES ('song-02','artist-02','Heights After Midnight','velvet-silo-heights-after-midnight','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3','https://placehold.co/640x640/0f172a/22d3ee?text=HI30',1,252,1438,784,486,CURRENT_TIMESTAMP,1);
INSERT OR IGNORE INTO chart_entries (id,artist_id,rank,previous_rank,movement,score,week_start_date,week_end_date,is_manual_override) VALUES ('chart-02','artist-02',2,2,'same',7438,date('now','weekday 1','-7 days'),date('now','weekday 0'),0);
INSERT OR IGNORE INTO artists (id,name,slug,bio,image_url,genre,city,neighborhood,social_links,streaming_links,is_approved,editorial_score,local_relevance_score) VALUES ('artist-03','Northside Static','northside-static','A fictional Houston underground act channeling Northside block energy, DIY studio texture, and late-night Gulf Coast melodies.','https://placehold.co/640x640/111827/f97316?text=NO','Punk Soul','Houston','Northside','{"instagram": "https://instagram.com/northside-static", "tiktok": "https://tiktok.com/@northside-static", "website": "https://example.com/northside-static"}','{"spotify": "https://open.spotify.com/search/northside-static", "youtube": "https://youtube.com/results?search_query=northside-static", "soundcloud": "https://soundcloud.com/northside-static", "bandcamp": "https://northside-static.bandcamp.com"}',1,7,7);
INSERT OR IGNORE INTO songs (id,artist_id,title,slug,audio_url,downloadable_file_url,cover_art_url,is_download_enabled,download_count,stream_count,unique_listener_count,external_click_count,approved_at,is_approved) VALUES ('song-03','artist-03','Loop 603 Lights','northside-static-loop-603-lights','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3','https://placehold.co/640x640/0f172a/22d3ee?text=HI30',1,248,1407,766,479,CURRENT_TIMESTAMP,1);
INSERT OR IGNORE INTO chart_entries (id,artist_id,rank,previous_rank,movement,score,week_start_date,week_end_date,is_manual_override) VALUES ('chart-03','artist-03',3,3,'same',7267,date('now','weekday 1','-7 days'),date('now','weekday 0'),0);
INSERT OR IGNORE INTO artists (id,name,slug,bio,image_url,genre,city,neighborhood,social_links,streaming_links,is_approved,editorial_score,local_relevance_score) VALUES ('artist-04','Gulf Freeway Ghosts','gulf-freeway-ghosts','A fictional Houston underground act channeling Southeast Houston block energy, DIY studio texture, and late-night Gulf Coast melodies.','https://placehold.co/640x640/111827/f97316?text=GU','Dream Pop','Houston','Southeast Houston','{"instagram": "https://instagram.com/gulf-freeway-ghosts", "tiktok": "https://tiktok.com/@gulf-freeway-ghosts", "website": "https://example.com/gulf-freeway-ghosts"}','{"spotify": "https://open.spotify.com/search/gulf-freeway-ghosts", "youtube": "https://youtube.com/results?search_query=gulf-freeway-ghosts", "soundcloud": "https://soundcloud.com/gulf-freeway-ghosts", "bandcamp": "https://gulf-freeway-ghosts.bandcamp.com"}',1,6,10);
INSERT OR IGNORE INTO songs (id,artist_id,title,slug,audio_url,downloadable_file_url,cover_art_url,is_download_enabled,download_count,stream_count,unique_listener_count,external_click_count,approved_at,is_approved) VALUES ('song-04','artist-04','Southeast Houston After Midnight','gulf-freeway-ghosts-southeast-houston-after-midnight','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3','https://placehold.co/640x640/0f172a/22d3ee?text=HI30',1,244,1376,748,472,CURRENT_TIMESTAMP,1);
INSERT OR IGNORE INTO chart_entries (id,artist_id,rank,previous_rank,movement,score,week_start_date,week_end_date,is_manual_override) VALUES ('chart-04','artist-04',4,5,'up',7128,date('now','weekday 1','-7 days'),date('now','weekday 0'),0);
INSERT OR IGNORE INTO artists (id,name,slug,bio,image_url,genre,city,neighborhood,social_links,streaming_links,is_approved,editorial_score,local_relevance_score) VALUES ('artist-05','Mango Curb','mango-curb','A fictional Houston underground act channeling Montrose block energy, DIY studio texture, and late-night Gulf Coast melodies.','https://placehold.co/640x640/111827/f97316?text=MA','Bedroom Pop','Houston','Montrose','{"instagram": "https://instagram.com/mango-curb", "tiktok": "https://tiktok.com/@mango-curb", "website": "https://example.com/mango-curb"}','{"spotify": "https://open.spotify.com/search/mango-curb", "youtube": "https://youtube.com/results?search_query=mango-curb", "soundcloud": "https://soundcloud.com/mango-curb", "bandcamp": "https://mango-curb.bandcamp.com"}',1,10,9);
INSERT OR IGNORE INTO songs (id,artist_id,title,slug,audio_url,downloadable_file_url,cover_art_url,is_download_enabled,download_count,stream_count,unique_listener_count,external_click_count,approved_at,is_approved) VALUES ('song-05','artist-05','Montrose After Midnight','mango-curb-montrose-after-midnight','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3','https://placehold.co/640x640/0f172a/22d3ee?text=HI30',1,240,1345,730,465,CURRENT_TIMESTAMP,1);
INSERT OR IGNORE INTO chart_entries (id,artist_id,rank,previous_rank,movement,score,week_start_date,week_end_date,is_manual_override) VALUES ('chart-05','artist-05',5,4,'down',7007,date('now','weekday 1','-7 days'),date('now','weekday 0'),0);
INSERT OR IGNORE INTO artists (id,name,slug,bio,image_url,genre,city,neighborhood,social_links,streaming_links,is_approved,editorial_score,local_relevance_score) VALUES ('artist-06','Clutch City Bloom','clutch-city-bloom','A fictional Houston underground act channeling South Park block energy, DIY studio texture, and late-night Gulf Coast melodies.','https://placehold.co/640x640/111827/f97316?text=CL','Hip-Hop','Houston','South Park','{"instagram": "https://instagram.com/clutch-city-bloom", "tiktok": "https://tiktok.com/@clutch-city-bloom", "website": "https://example.com/clutch-city-bloom"}','{"spotify": "https://open.spotify.com/search/clutch-city-bloom", "youtube": "https://youtube.com/results?search_query=clutch-city-bloom", "soundcloud": "https://soundcloud.com/clutch-city-bloom", "bandcamp": "https://clutch-city-bloom.bandcamp.com"}',1,9,8);
INSERT OR IGNORE INTO songs (id,artist_id,title,slug,audio_url,downloadable_file_url,cover_art_url,is_download_enabled,download_count,stream_count,unique_listener_count,external_click_count,approved_at,is_approved) VALUES ('song-06','artist-06','Loop 606 Lights','clutch-city-bloom-loop-606-lights','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3','https://placehold.co/640x640/0f172a/22d3ee?text=HI30',1,236,1314,712,458,CURRENT_TIMESTAMP,1);
INSERT OR IGNORE INTO chart_entries (id,artist_id,rank,previous_rank,movement,score,week_start_date,week_end_date,is_manual_override) VALUES ('chart-06','artist-06',6,6,'same',6836,date('now','weekday 1','-7 days'),date('now','weekday 0'),0);
INSERT OR IGNORE INTO artists (id,name,slug,bio,image_url,genre,city,neighborhood,social_links,streaming_links,is_approved,editorial_score,local_relevance_score) VALUES ('artist-07','Buffalo Bay Synth','buffalo-bay-synth','A fictional Houston underground act channeling EaDo block energy, DIY studio texture, and late-night Gulf Coast melodies.','https://placehold.co/640x640/111827/f97316?text=BU','Electronic','Houston','EaDo','{"instagram": "https://instagram.com/buffalo-bay-synth", "tiktok": "https://tiktok.com/@buffalo-bay-synth", "website": "https://example.com/buffalo-bay-synth"}','{"spotify": "https://open.spotify.com/search/buffalo-bay-synth", "youtube": "https://youtube.com/results?search_query=buffalo-bay-synth", "soundcloud": "https://soundcloud.com/buffalo-bay-synth", "bandcamp": "https://buffalo-bay-synth.bandcamp.com"}',1,8,7);
INSERT OR IGNORE INTO songs (id,artist_id,title,slug,audio_url,downloadable_file_url,cover_art_url,is_download_enabled,download_count,stream_count,unique_listener_count,external_click_count,approved_at,is_approved) VALUES ('song-07','artist-07','EaDo After Midnight','buffalo-bay-synth-eado-after-midnight','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3','https://placehold.co/640x640/0f172a/22d3ee?text=HI30',1,232,1283,694,451,CURRENT_TIMESTAMP,1);
INSERT OR IGNORE INTO chart_entries (id,artist_id,rank,previous_rank,movement,score,week_start_date,week_end_date,is_manual_override) VALUES ('chart-07','artist-07',7,7,'same',6665,date('now','weekday 1','-7 days'),date('now','weekday 0'),0);
INSERT OR IGNORE INTO artists (id,name,slug,bio,image_url,genre,city,neighborhood,social_links,streaming_links,is_approved,editorial_score,local_relevance_score) VALUES ('artist-08','Prairie View Drive','prairie-view-drive','A fictional Houston underground act channeling Acres Homes block energy, DIY studio texture, and late-night Gulf Coast melodies.','https://placehold.co/640x640/111827/f97316?text=PR','Folk Rap','Houston','Acres Homes','{"instagram": "https://instagram.com/prairie-view-drive", "tiktok": "https://tiktok.com/@prairie-view-drive", "website": "https://example.com/prairie-view-drive"}','{"spotify": "https://open.spotify.com/search/prairie-view-drive", "youtube": "https://youtube.com/results?search_query=prairie-view-drive", "soundcloud": "https://soundcloud.com/prairie-view-drive", "bandcamp": "https://prairie-view-drive.bandcamp.com"}',1,7,10);
INSERT OR IGNORE INTO songs (id,artist_id,title,slug,audio_url,downloadable_file_url,cover_art_url,is_download_enabled,download_count,stream_count,unique_listener_count,external_click_count,approved_at,is_approved) VALUES ('song-08','artist-08','Acres Homes After Midnight','prairie-view-drive-acres-homes-after-midnight','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3','https://placehold.co/640x640/0f172a/22d3ee?text=HI30',1,228,1252,676,444,CURRENT_TIMESTAMP,1);
INSERT OR IGNORE INTO chart_entries (id,artist_id,rank,previous_rank,movement,score,week_start_date,week_end_date,is_manual_override) VALUES ('chart-08','artist-08',8,9,'up',6526,date('now','weekday 1','-7 days'),date('now','weekday 0'),0);
INSERT OR IGNORE INTO artists (id,name,slug,bio,image_url,genre,city,neighborhood,social_links,streaming_links,is_approved,editorial_score,local_relevance_score) VALUES ('artist-09','Ship Channel Choir','ship-channel-choir','A fictional Houston underground act channeling Second Ward block energy, DIY studio texture, and late-night Gulf Coast melodies.','https://placehold.co/640x640/111827/f97316?text=SH','Industrial Pop','Houston','Second Ward','{"instagram": "https://instagram.com/ship-channel-choir", "tiktok": "https://tiktok.com/@ship-channel-choir", "website": "https://example.com/ship-channel-choir"}','{"spotify": "https://open.spotify.com/search/ship-channel-choir", "youtube": "https://youtube.com/results?search_query=ship-channel-choir", "soundcloud": "https://soundcloud.com/ship-channel-choir", "bandcamp": "https://ship-channel-choir.bandcamp.com"}',1,6,9);
INSERT OR IGNORE INTO songs (id,artist_id,title,slug,audio_url,downloadable_file_url,cover_art_url,is_download_enabled,download_count,stream_count,unique_listener_count,external_click_count,approved_at,is_approved) VALUES ('song-09','artist-09','Loop 609 Lights','ship-channel-choir-loop-609-lights','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3','https://placehold.co/640x640/0f172a/22d3ee?text=HI30',1,224,1221,658,437,CURRENT_TIMESTAMP,1);
INSERT OR IGNORE INTO chart_entries (id,artist_id,rank,previous_rank,movement,score,week_start_date,week_end_date,is_manual_override) VALUES ('chart-09','artist-09',9,9,'same',6355,date('now','weekday 1','-7 days'),date('now','weekday 0'),0);
INSERT OR IGNORE INTO artists (id,name,slug,bio,image_url,genre,city,neighborhood,social_links,streaming_links,is_approved,editorial_score,local_relevance_score) VALUES ('artist-10','Sienna Afterhours','sienna-afterhours','A fictional Houston underground act channeling Missouri City block energy, DIY studio texture, and late-night Gulf Coast melodies.','https://placehold.co/640x640/111827/f97316?text=SI','Neo-Soul','Houston','Missouri City','{"instagram": "https://instagram.com/sienna-afterhours", "tiktok": "https://tiktok.com/@sienna-afterhours", "website": "https://example.com/sienna-afterhours"}','{"spotify": "https://open.spotify.com/search/sienna-afterhours", "youtube": "https://youtube.com/results?search_query=sienna-afterhours", "soundcloud": "https://soundcloud.com/sienna-afterhours", "bandcamp": "https://sienna-afterhours.bandcamp.com"}',1,10,8);
INSERT OR IGNORE INTO songs (id,artist_id,title,slug,audio_url,downloadable_file_url,cover_art_url,is_download_enabled,download_count,stream_count,unique_listener_count,external_click_count,approved_at,is_approved) VALUES ('song-10','artist-10','Missouri City After Midnight','sienna-afterhours-missouri-city-after-midnight','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3','https://placehold.co/640x640/0f172a/22d3ee?text=HI30',1,220,1190,640,430,CURRENT_TIMESTAMP,1);
INSERT OR IGNORE INTO chart_entries (id,artist_id,rank,previous_rank,movement,score,week_start_date,week_end_date,is_manual_override) VALUES ('chart-10','artist-10',10,9,'down',6219,date('now','weekday 1','-7 days'),date('now','weekday 0'),0);
INSERT OR IGNORE INTO artists (id,name,slug,bio,image_url,genre,city,neighborhood,social_links,streaming_links,is_approved,editorial_score,local_relevance_score) VALUES ('artist-11','Telegraph Oaks','telegraph-oaks','A fictional Houston underground act channeling Garden Oaks block energy, DIY studio texture, and late-night Gulf Coast melodies.','https://placehold.co/640x640/111827/f97316?text=TE','Garage Rock','Houston','Garden Oaks','{"instagram": "https://instagram.com/telegraph-oaks", "tiktok": "https://tiktok.com/@telegraph-oaks", "website": "https://example.com/telegraph-oaks"}','{"spotify": "https://open.spotify.com/search/telegraph-oaks", "youtube": "https://youtube.com/results?search_query=telegraph-oaks", "soundcloud": "https://soundcloud.com/telegraph-oaks", "bandcamp": "https://telegraph-oaks.bandcamp.com"}',1,9,7);
INSERT OR IGNORE INTO songs (id,artist_id,title,slug,audio_url,downloadable_file_url,cover_art_url,is_download_enabled,download_count,stream_count,unique_listener_count,external_click_count,approved_at,is_approved) VALUES ('song-11','artist-11','Garden Oaks After Midnight','telegraph-oaks-garden-oaks-after-midnight','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3','https://placehold.co/640x640/0f172a/22d3ee?text=HI30',1,216,1159,622,423,CURRENT_TIMESTAMP,1);
INSERT OR IGNORE INTO chart_entries (id,artist_id,rank,previous_rank,movement,score,week_start_date,week_end_date,is_manual_override) VALUES ('chart-11','artist-11',11,11,'same',6048,date('now','weekday 1','-7 days'),date('now','weekday 0'),0);
INSERT OR IGNORE INTO artists (id,name,slug,bio,image_url,genre,city,neighborhood,social_links,streaming_links,is_approved,editorial_score,local_relevance_score) VALUES ('artist-12','Cullen Moon','cullen-moon','A fictional Houston underground act channeling MacGregor block energy, DIY studio texture, and late-night Gulf Coast melodies.','https://placehold.co/640x640/111827/f97316?text=CU','Alt-Country','Houston','MacGregor','{"instagram": "https://instagram.com/cullen-moon", "tiktok": "https://tiktok.com/@cullen-moon", "website": "https://example.com/cullen-moon"}','{"spotify": "https://open.spotify.com/search/cullen-moon", "youtube": "https://youtube.com/results?search_query=cullen-moon", "soundcloud": "https://soundcloud.com/cullen-moon", "bandcamp": "https://cullen-moon.bandcamp.com"}',1,8,10);
INSERT OR IGNORE INTO songs (id,artist_id,title,slug,audio_url,downloadable_file_url,cover_art_url,is_download_enabled,download_count,stream_count,unique_listener_count,external_click_count,approved_at,is_approved) VALUES ('song-12','artist-12','Loop 612 Lights','cullen-moon-loop-612-lights','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3','https://placehold.co/640x640/0f172a/22d3ee?text=HI30',1,212,1128,604,416,CURRENT_TIMESTAMP,1);
INSERT OR IGNORE INTO chart_entries (id,artist_id,rank,previous_rank,movement,score,week_start_date,week_end_date,is_manual_override) VALUES ('chart-12','artist-12',12,13,'up',5909,date('now','weekday 1','-7 days'),date('now','weekday 0'),0);
INSERT OR IGNORE INTO artists (id,name,slug,bio,image_url,genre,city,neighborhood,social_links,streaming_links,is_approved,editorial_score,local_relevance_score) VALUES ('artist-13','Alief Frequencies','alief-frequencies','A fictional Houston underground act channeling Alief block energy, DIY studio texture, and late-night Gulf Coast melodies.','https://placehold.co/640x640/111827/f97316?text=AL','Jersey Club','Houston','Alief','{"instagram": "https://instagram.com/alief-frequencies", "tiktok": "https://tiktok.com/@alief-frequencies", "website": "https://example.com/alief-frequencies"}','{"spotify": "https://open.spotify.com/search/alief-frequencies", "youtube": "https://youtube.com/results?search_query=alief-frequencies", "soundcloud": "https://soundcloud.com/alief-frequencies", "bandcamp": "https://alief-frequencies.bandcamp.com"}',1,7,9);
INSERT OR IGNORE INTO songs (id,artist_id,title,slug,audio_url,downloadable_file_url,cover_art_url,is_download_enabled,download_count,stream_count,unique_listener_count,external_click_count,approved_at,is_approved) VALUES ('song-13','artist-13','Alief After Midnight','alief-frequencies-alief-after-midnight','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3','https://placehold.co/640x640/0f172a/22d3ee?text=HI30',1,208,1097,586,409,CURRENT_TIMESTAMP,1);
INSERT OR IGNORE INTO chart_entries (id,artist_id,rank,previous_rank,movement,score,week_start_date,week_end_date,is_manual_override) VALUES ('chart-13','artist-13',13,13,'same',5738,date('now','weekday 1','-7 days'),date('now','weekday 0'),0);
INSERT OR IGNORE INTO artists (id,name,slug,bio,image_url,genre,city,neighborhood,social_links,streaming_links,is_approved,editorial_score,local_relevance_score) VALUES ('artist-14','Magnolia Transit','magnolia-transit','A fictional Houston underground act channeling Magnolia Park block energy, DIY studio texture, and late-night Gulf Coast melodies.','https://placehold.co/640x640/111827/f97316?text=MA','Latin Indie','Houston','Magnolia Park','{"instagram": "https://instagram.com/magnolia-transit", "tiktok": "https://tiktok.com/@magnolia-transit", "website": "https://example.com/magnolia-transit"}','{"spotify": "https://open.spotify.com/search/magnolia-transit", "youtube": "https://youtube.com/results?search_query=magnolia-transit", "soundcloud": "https://soundcloud.com/magnolia-transit", "bandcamp": "https://magnolia-transit.bandcamp.com"}',1,6,8);
INSERT OR IGNORE INTO songs (id,artist_id,title,slug,audio_url,downloadable_file_url,cover_art_url,is_download_enabled,download_count,stream_count,unique_listener_count,external_click_count,approved_at,is_approved) VALUES ('song-14','artist-14','Magnolia Park After Midnight','magnolia-transit-magnolia-park-after-midnight','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3','https://placehold.co/640x640/0f172a/22d3ee?text=HI30',1,204,1066,568,402,CURRENT_TIMESTAMP,1);
INSERT OR IGNORE INTO chart_entries (id,artist_id,rank,previous_rank,movement,score,week_start_date,week_end_date,is_manual_override) VALUES ('chart-14','artist-14',14,14,'same',5567,date('now','weekday 1','-7 days'),date('now','weekday 0'),0);
INSERT OR IGNORE INTO artists (id,name,slug,bio,image_url,genre,city,neighborhood,social_links,streaming_links,is_approved,editorial_score,local_relevance_score) VALUES ('artist-15','Space City Velvet','space-city-velvet','A fictional Houston underground act channeling Midtown block energy, DIY studio texture, and late-night Gulf Coast melodies.','https://placehold.co/640x640/111827/f97316?text=SP','Synthwave','Houston','Midtown','{"instagram": "https://instagram.com/space-city-velvet", "tiktok": "https://tiktok.com/@space-city-velvet", "website": "https://example.com/space-city-velvet"}','{"spotify": "https://open.spotify.com/search/space-city-velvet", "youtube": "https://youtube.com/results?search_query=space-city-velvet", "soundcloud": "https://soundcloud.com/space-city-velvet", "bandcamp": "https://space-city-velvet.bandcamp.com"}',1,10,7);
INSERT OR IGNORE INTO songs (id,artist_id,title,slug,audio_url,downloadable_file_url,cover_art_url,is_download_enabled,download_count,stream_count,unique_listener_count,external_click_count,approved_at,is_approved) VALUES ('song-15','artist-15','Loop 615 Lights','space-city-velvet-loop-615-lights','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-16.mp3','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-16.mp3','https://placehold.co/640x640/0f172a/22d3ee?text=HI30',1,200,1035,550,395,CURRENT_TIMESTAMP,1);
INSERT OR IGNORE INTO chart_entries (id,artist_id,rank,previous_rank,movement,score,week_start_date,week_end_date,is_manual_override) VALUES ('chart-15','artist-15',15,14,'down',5446,date('now','weekday 1','-7 days'),date('now','weekday 0'),0);
INSERT OR IGNORE INTO artists (id,name,slug,bio,image_url,genre,city,neighborhood,social_links,streaming_links,is_approved,editorial_score,local_relevance_score) VALUES ('artist-16','Hobby Night Run','hobby-night-run','A fictional Houston underground act channeling Gulfgate block energy, DIY studio texture, and late-night Gulf Coast melodies.','https://placehold.co/640x640/111827/f97316?text=HO','Trap Jazz','Houston','Gulfgate','{"instagram": "https://instagram.com/hobby-night-run", "tiktok": "https://tiktok.com/@hobby-night-run", "website": "https://example.com/hobby-night-run"}','{"spotify": "https://open.spotify.com/search/hobby-night-run", "youtube": "https://youtube.com/results?search_query=hobby-night-run", "soundcloud": "https://soundcloud.com/hobby-night-run", "bandcamp": "https://hobby-night-run.bandcamp.com"}',1,9,10);
INSERT OR IGNORE INTO songs (id,artist_id,title,slug,audio_url,downloadable_file_url,cover_art_url,is_download_enabled,download_count,stream_count,unique_listener_count,external_click_count,approved_at,is_approved) VALUES ('song-16','artist-16','Gulfgate After Midnight','hobby-night-run-gulfgate-after-midnight','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3','https://placehold.co/640x640/0f172a/22d3ee?text=HI30',1,196,1004,532,388,CURRENT_TIMESTAMP,1);
INSERT OR IGNORE INTO chart_entries (id,artist_id,rank,previous_rank,movement,score,week_start_date,week_end_date,is_manual_override) VALUES ('chart-16','artist-16',16,17,'up',5307,date('now','weekday 1','-7 days'),date('now','weekday 0'),0);
INSERT OR IGNORE INTO artists (id,name,slug,bio,image_url,genre,city,neighborhood,social_links,streaming_links,is_approved,editorial_score,local_relevance_score) VALUES ('artist-17','Brays Static','brays-static','A fictional Houston underground act channeling Meyerland block energy, DIY studio texture, and late-night Gulf Coast melodies.','https://placehold.co/640x640/111827/f97316?text=BR','Noise Pop','Houston','Meyerland','{"instagram": "https://instagram.com/brays-static", "tiktok": "https://tiktok.com/@brays-static", "website": "https://example.com/brays-static"}','{"spotify": "https://open.spotify.com/search/brays-static", "youtube": "https://youtube.com/results?search_query=brays-static", "soundcloud": "https://soundcloud.com/brays-static", "bandcamp": "https://brays-static.bandcamp.com"}',1,8,9);
INSERT OR IGNORE INTO songs (id,artist_id,title,slug,audio_url,downloadable_file_url,cover_art_url,is_download_enabled,download_count,stream_count,unique_listener_count,external_click_count,approved_at,is_approved) VALUES ('song-17','artist-17','Meyerland After Midnight','brays-static-meyerland-after-midnight','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3','https://placehold.co/640x640/0f172a/22d3ee?text=HI30',1,192,973,514,381,CURRENT_TIMESTAMP,1);
INSERT OR IGNORE INTO chart_entries (id,artist_id,rank,previous_rank,movement,score,week_start_date,week_end_date,is_manual_override) VALUES ('chart-17','artist-17',17,17,'same',5136,date('now','weekday 1','-7 days'),date('now','weekday 0'),0);
INSERT OR IGNORE INTO artists (id,name,slug,bio,image_url,genre,city,neighborhood,social_links,streaming_links,is_approved,editorial_score,local_relevance_score) VALUES ('artist-18','Westheimer Weather','westheimer-weather','A fictional Houston underground act channeling Upper Kirby block energy, DIY studio texture, and late-night Gulf Coast melodies.','https://placehold.co/640x640/111827/f97316?text=WE','Indie Pop','Houston','Upper Kirby','{"instagram": "https://instagram.com/westheimer-weather", "tiktok": "https://tiktok.com/@westheimer-weather", "website": "https://example.com/westheimer-weather"}','{"spotify": "https://open.spotify.com/search/westheimer-weather", "youtube": "https://youtube.com/results?search_query=westheimer-weather", "soundcloud": "https://soundcloud.com/westheimer-weather", "bandcamp": "https://westheimer-weather.bandcamp.com"}',1,7,8);
INSERT OR IGNORE INTO songs (id,artist_id,title,slug,audio_url,downloadable_file_url,cover_art_url,is_download_enabled,download_count,stream_count,unique_listener_count,external_click_count,approved_at,is_approved) VALUES ('song-18','artist-18','Loop 618 Lights','westheimer-weather-loop-618-lights','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3','https://placehold.co/640x640/0f172a/22d3ee?text=HI30',1,188,942,496,374,CURRENT_TIMESTAMP,1);
INSERT OR IGNORE INTO chart_entries (id,artist_id,rank,previous_rank,movement,score,week_start_date,week_end_date,is_manual_override) VALUES ('chart-18','artist-18',18,18,'same',4965,date('now','weekday 1','-7 days'),date('now','weekday 0'),0);
INSERT OR IGNORE INTO artists (id,name,slug,bio,image_url,genre,city,neighborhood,social_links,streaming_links,is_approved,editorial_score,local_relevance_score) VALUES ('artist-19','Trillium Park','trillium-park','A fictional Houston underground act channeling Sharpstown block energy, DIY studio texture, and late-night Gulf Coast melodies.','https://placehold.co/640x640/111827/f97316?text=TR','Lo-Fi Rap','Houston','Sharpstown','{"instagram": "https://instagram.com/trillium-park", "tiktok": "https://tiktok.com/@trillium-park", "website": "https://example.com/trillium-park"}','{"spotify": "https://open.spotify.com/search/trillium-park", "youtube": "https://youtube.com/results?search_query=trillium-park", "soundcloud": "https://soundcloud.com/trillium-park", "bandcamp": "https://trillium-park.bandcamp.com"}',1,6,7);
INSERT OR IGNORE INTO songs (id,artist_id,title,slug,audio_url,downloadable_file_url,cover_art_url,is_download_enabled,download_count,stream_count,unique_listener_count,external_click_count,approved_at,is_approved) VALUES ('song-19','artist-19','Sharpstown After Midnight','trillium-park-sharpstown-after-midnight','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3','https://placehold.co/640x640/0f172a/22d3ee?text=HI30',1,184,911,478,367,CURRENT_TIMESTAMP,1);
INSERT OR IGNORE INTO chart_entries (id,artist_id,rank,previous_rank,movement,score,week_start_date,week_end_date,is_manual_override) VALUES ('chart-19','artist-19',19,19,'same',4794,date('now','weekday 1','-7 days'),date('now','weekday 0'),0);
INSERT OR IGNORE INTO artists (id,name,slug,bio,image_url,genre,city,neighborhood,social_links,streaming_links,is_approved,editorial_score,local_relevance_score) VALUES ('artist-20','Canal Street Aura','canal-street-aura','A fictional Houston underground act channeling East End block energy, DIY studio texture, and late-night Gulf Coast melodies.','https://placehold.co/640x640/111827/f97316?text=CA','Cumbia Fusion','Houston','East End','{"instagram": "https://instagram.com/canal-street-aura", "tiktok": "https://tiktok.com/@canal-street-aura", "website": "https://example.com/canal-street-aura"}','{"spotify": "https://open.spotify.com/search/canal-street-aura", "youtube": "https://youtube.com/results?search_query=canal-street-aura", "soundcloud": "https://soundcloud.com/canal-street-aura", "bandcamp": "https://canal-street-aura.bandcamp.com"}',1,10,10);
INSERT OR IGNORE INTO songs (id,artist_id,title,slug,audio_url,downloadable_file_url,cover_art_url,is_download_enabled,download_count,stream_count,unique_listener_count,external_click_count,approved_at,is_approved) VALUES ('song-20','artist-20','East End After Midnight','canal-street-aura-east-end-after-midnight','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3','https://placehold.co/640x640/0f172a/22d3ee?text=HI30',1,180,880,460,360,CURRENT_TIMESTAMP,1);
INSERT OR IGNORE INTO chart_entries (id,artist_id,rank,previous_rank,movement,score,week_start_date,week_end_date,is_manual_override) VALUES ('chart-20','artist-20',20,21,'up',4705,date('now','weekday 1','-7 days'),date('now','weekday 0'),0);
INSERT OR IGNORE INTO artists (id,name,slug,bio,image_url,genre,city,neighborhood,social_links,streaming_links,is_approved,editorial_score,local_relevance_score) VALUES ('artist-21','Kirby Chrome','kirby-chrome','A fictional Houston underground act channeling Rice Village block energy, DIY studio texture, and late-night Gulf Coast melodies.','https://placehold.co/640x640/111827/f97316?text=KI','Hyperpop','Houston','Rice Village','{"instagram": "https://instagram.com/kirby-chrome", "tiktok": "https://tiktok.com/@kirby-chrome", "website": "https://example.com/kirby-chrome"}','{"spotify": "https://open.spotify.com/search/kirby-chrome", "youtube": "https://youtube.com/results?search_query=kirby-chrome", "soundcloud": "https://soundcloud.com/kirby-chrome", "bandcamp": "https://kirby-chrome.bandcamp.com"}',1,9,9);
INSERT OR IGNORE INTO songs (id,artist_id,title,slug,audio_url,downloadable_file_url,cover_art_url,is_download_enabled,download_count,stream_count,unique_listener_count,external_click_count,approved_at,is_approved) VALUES ('song-21','artist-21','Loop 621 Lights','kirby-chrome-loop-621-lights','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3','https://placehold.co/640x640/0f172a/22d3ee?text=HI30',1,176,849,442,353,CURRENT_TIMESTAMP,1);
INSERT OR IGNORE INTO chart_entries (id,artist_id,rank,previous_rank,movement,score,week_start_date,week_end_date,is_manual_override) VALUES ('chart-21','artist-21',21,21,'same',4534,date('now','weekday 1','-7 days'),date('now','weekday 0'),0);
INSERT OR IGNORE INTO artists (id,name,slug,bio,image_url,genre,city,neighborhood,social_links,streaming_links,is_approved,editorial_score,local_relevance_score) VALUES ('artist-22','Fondren Futures','fondren-futures','A fictional Houston underground act channeling Fondren block energy, DIY studio texture, and late-night Gulf Coast melodies.','https://placehold.co/640x640/111827/f97316?text=FO','Afrobeat','Houston','Fondren','{"instagram": "https://instagram.com/fondren-futures", "tiktok": "https://tiktok.com/@fondren-futures", "website": "https://example.com/fondren-futures"}','{"spotify": "https://open.spotify.com/search/fondren-futures", "youtube": "https://youtube.com/results?search_query=fondren-futures", "soundcloud": "https://soundcloud.com/fondren-futures", "bandcamp": "https://fondren-futures.bandcamp.com"}',1,8,8);
INSERT OR IGNORE INTO songs (id,artist_id,title,slug,audio_url,downloadable_file_url,cover_art_url,is_download_enabled,download_count,stream_count,unique_listener_count,external_click_count,approved_at,is_approved) VALUES ('song-22','artist-22','Fondren After Midnight','fondren-futures-fondren-after-midnight','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3','https://placehold.co/640x640/0f172a/22d3ee?text=HI30',1,172,818,424,346,CURRENT_TIMESTAMP,1);
INSERT OR IGNORE INTO chart_entries (id,artist_id,rank,previous_rank,movement,score,week_start_date,week_end_date,is_manual_override) VALUES ('chart-22','artist-22',22,22,'same',4353,date('now','weekday 1','-7 days'),date('now','weekday 0'),0);
INSERT OR IGNORE INTO artists (id,name,slug,bio,image_url,genre,city,neighborhood,social_links,streaming_links,is_approved,editorial_score,local_relevance_score) VALUES ('artist-23','Sawyer Yards Signal','sawyer-yards-signal','A fictional Houston underground act channeling First Ward block energy, DIY studio texture, and late-night Gulf Coast melodies.','https://placehold.co/640x640/111827/f97316?text=SA','Art Rock','Houston','First Ward','{"instagram": "https://instagram.com/sawyer-yards-signal", "tiktok": "https://tiktok.com/@sawyer-yards-signal", "website": "https://example.com/sawyer-yards-signal"}','{"spotify": "https://open.spotify.com/search/sawyer-yards-signal", "youtube": "https://youtube.com/results?search_query=sawyer-yards-signal", "soundcloud": "https://soundcloud.com/sawyer-yards-signal", "bandcamp": "https://sawyer-yards-signal.bandcamp.com"}',1,7,7);
INSERT OR IGNORE INTO songs (id,artist_id,title,slug,audio_url,downloadable_file_url,cover_art_url,is_download_enabled,download_count,stream_count,unique_listener_count,external_click_count,approved_at,is_approved) VALUES ('song-23','artist-23','First Ward After Midnight','sawyer-yards-signal-first-ward-after-midnight','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3','https://placehold.co/640x640/0f172a/22d3ee?text=HI30',1,168,787,406,339,CURRENT_TIMESTAMP,1);
INSERT OR IGNORE INTO chart_entries (id,artist_id,rank,previous_rank,movement,score,week_start_date,week_end_date,is_manual_override) VALUES ('chart-23','artist-23',23,23,'same',4182,date('now','weekday 1','-7 days'),date('now','weekday 0'),0);
INSERT OR IGNORE INTO artists (id,name,slug,bio,image_url,genre,city,neighborhood,social_links,streaming_links,is_approved,editorial_score,local_relevance_score) VALUES ('artist-24','Greenpoint Cassette','greenpoint-cassette','A fictional Houston underground act channeling Greenspoint block energy, DIY studio texture, and late-night Gulf Coast melodies.','https://placehold.co/640x640/111827/f97316?text=GR','Shoegaze','Houston','Greenspoint','{"instagram": "https://instagram.com/greenpoint-cassette", "tiktok": "https://tiktok.com/@greenpoint-cassette", "website": "https://example.com/greenpoint-cassette"}','{"spotify": "https://open.spotify.com/search/greenpoint-cassette", "youtube": "https://youtube.com/results?search_query=greenpoint-cassette", "soundcloud": "https://soundcloud.com/greenpoint-cassette", "bandcamp": "https://greenpoint-cassette.bandcamp.com"}',1,6,10);
INSERT OR IGNORE INTO songs (id,artist_id,title,slug,audio_url,downloadable_file_url,cover_art_url,is_download_enabled,download_count,stream_count,unique_listener_count,external_click_count,approved_at,is_approved) VALUES ('song-24','artist-24','Loop 624 Lights','greenpoint-cassette-loop-624-lights','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3','https://placehold.co/640x640/0f172a/22d3ee?text=HI30',1,164,756,388,332,CURRENT_TIMESTAMP,1);
INSERT OR IGNORE INTO chart_entries (id,artist_id,rank,previous_rank,movement,score,week_start_date,week_end_date,is_manual_override) VALUES ('chart-24','artist-24',24,25,'up',4043,date('now','weekday 1','-7 days'),date('now','weekday 0'),0);
INSERT OR IGNORE INTO artists (id,name,slug,bio,image_url,genre,city,neighborhood,social_links,streaming_links,is_approved,editorial_score,local_relevance_score) VALUES ('artist-25','Lawndale Lanterns','lawndale-lanterns','A fictional Houston underground act channeling Eastwood block energy, DIY studio texture, and late-night Gulf Coast melodies.','https://placehold.co/640x640/111827/f97316?text=LA','Soul','Houston','Eastwood','{"instagram": "https://instagram.com/lawndale-lanterns", "tiktok": "https://tiktok.com/@lawndale-lanterns", "website": "https://example.com/lawndale-lanterns"}','{"spotify": "https://open.spotify.com/search/lawndale-lanterns", "youtube": "https://youtube.com/results?search_query=lawndale-lanterns", "soundcloud": "https://soundcloud.com/lawndale-lanterns", "bandcamp": "https://lawndale-lanterns.bandcamp.com"}',1,10,9);
INSERT OR IGNORE INTO songs (id,artist_id,title,slug,audio_url,downloadable_file_url,cover_art_url,is_download_enabled,download_count,stream_count,unique_listener_count,external_click_count,approved_at,is_approved) VALUES ('song-25','artist-25','Eastwood After Midnight','lawndale-lanterns-eastwood-after-midnight','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-10.mp3','https://placehold.co/640x640/0f172a/22d3ee?text=HI30',1,160,725,370,325,CURRENT_TIMESTAMP,1);
INSERT OR IGNORE INTO chart_entries (id,artist_id,rank,previous_rank,movement,score,week_start_date,week_end_date,is_manual_override) VALUES ('chart-25','artist-25',25,24,'down',3922,date('now','weekday 1','-7 days'),date('now','weekday 0'),0);
INSERT OR IGNORE INTO artists (id,name,slug,bio,image_url,genre,city,neighborhood,social_links,streaming_links,is_approved,editorial_score,local_relevance_score) VALUES ('artist-26','Clear Lake Mirage','clear-lake-mirage','A fictional Houston underground act channeling Clear Lake block energy, DIY studio texture, and late-night Gulf Coast melodies.','https://placehold.co/640x640/111827/f97316?text=CL','Ambient','Houston','Clear Lake','{"instagram": "https://instagram.com/clear-lake-mirage", "tiktok": "https://tiktok.com/@clear-lake-mirage", "website": "https://example.com/clear-lake-mirage"}','{"spotify": "https://open.spotify.com/search/clear-lake-mirage", "youtube": "https://youtube.com/results?search_query=clear-lake-mirage", "soundcloud": "https://soundcloud.com/clear-lake-mirage", "bandcamp": "https://clear-lake-mirage.bandcamp.com"}',1,9,8);
INSERT OR IGNORE INTO songs (id,artist_id,title,slug,audio_url,downloadable_file_url,cover_art_url,is_download_enabled,download_count,stream_count,unique_listener_count,external_click_count,approved_at,is_approved) VALUES ('song-26','artist-26','Clear Lake After Midnight','clear-lake-mirage-clear-lake-after-midnight','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-11.mp3','https://placehold.co/640x640/0f172a/22d3ee?text=HI30',1,156,694,352,318,CURRENT_TIMESTAMP,1);
INSERT OR IGNORE INTO chart_entries (id,artist_id,rank,previous_rank,movement,score,week_start_date,week_end_date,is_manual_override) VALUES ('chart-26','artist-26',26,26,'same',3751,date('now','weekday 1','-7 days'),date('now','weekday 0'),0);
INSERT OR IGNORE INTO artists (id,name,slug,bio,image_url,genre,city,neighborhood,social_links,streaming_links,is_approved,editorial_score,local_relevance_score) VALUES ('artist-27','Mo City Relays','mo-city-relays','A fictional Houston underground act channeling Southwest Houston block energy, DIY studio texture, and late-night Gulf Coast melodies.','https://placehold.co/640x640/111827/f97316?text=MO','Rap','Houston','Southwest Houston','{"instagram": "https://instagram.com/mo-city-relays", "tiktok": "https://tiktok.com/@mo-city-relays", "website": "https://example.com/mo-city-relays"}','{"spotify": "https://open.spotify.com/search/mo-city-relays", "youtube": "https://youtube.com/results?search_query=mo-city-relays", "soundcloud": "https://soundcloud.com/mo-city-relays", "bandcamp": "https://mo-city-relays.bandcamp.com"}',1,8,7);
INSERT OR IGNORE INTO songs (id,artist_id,title,slug,audio_url,downloadable_file_url,cover_art_url,is_download_enabled,download_count,stream_count,unique_listener_count,external_click_count,approved_at,is_approved) VALUES ('song-27','artist-27','Loop 627 Lights','mo-city-relays-loop-627-lights','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3','https://placehold.co/640x640/0f172a/22d3ee?text=HI30',1,152,663,334,311,CURRENT_TIMESTAMP,1);
INSERT OR IGNORE INTO chart_entries (id,artist_id,rank,previous_rank,movement,score,week_start_date,week_end_date,is_manual_override) VALUES ('chart-27','artist-27',27,27,'same',3580,date('now','weekday 1','-7 days'),date('now','weekday 0'),0);
INSERT OR IGNORE INTO artists (id,name,slug,bio,image_url,genre,city,neighborhood,social_links,streaming_links,is_approved,editorial_score,local_relevance_score) VALUES ('artist-28','Hiram Clarke Hymns','hiram-clarke-hymns','A fictional Houston underground act channeling Hiram Clarke block energy, DIY studio texture, and late-night Gulf Coast melodies.','https://placehold.co/640x640/111827/f97316?text=HI','Gospel Drill','Houston','Hiram Clarke','{"instagram": "https://instagram.com/hiram-clarke-hymns", "tiktok": "https://tiktok.com/@hiram-clarke-hymns", "website": "https://example.com/hiram-clarke-hymns"}','{"spotify": "https://open.spotify.com/search/hiram-clarke-hymns", "youtube": "https://youtube.com/results?search_query=hiram-clarke-hymns", "soundcloud": "https://soundcloud.com/hiram-clarke-hymns", "bandcamp": "https://hiram-clarke-hymns.bandcamp.com"}',1,7,10);
INSERT OR IGNORE INTO songs (id,artist_id,title,slug,audio_url,downloadable_file_url,cover_art_url,is_download_enabled,download_count,stream_count,unique_listener_count,external_click_count,approved_at,is_approved) VALUES ('song-28','artist-28','Hiram Clarke After Midnight','hiram-clarke-hymns-hiram-clarke-after-midnight','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-13.mp3','https://placehold.co/640x640/0f172a/22d3ee?text=HI30',1,148,632,316,304,CURRENT_TIMESTAMP,1);
INSERT OR IGNORE INTO chart_entries (id,artist_id,rank,previous_rank,movement,score,week_start_date,week_end_date,is_manual_override) VALUES ('chart-28','artist-28',28,29,'up',3441,date('now','weekday 1','-7 days'),date('now','weekday 0'),0);
INSERT OR IGNORE INTO artists (id,name,slug,bio,image_url,genre,city,neighborhood,social_links,streaming_links,is_approved,editorial_score,local_relevance_score) VALUES ('artist-29','Emancipation Echo','emancipation-echo','A fictional Houston underground act channeling Third Ward block energy, DIY studio texture, and late-night Gulf Coast melodies.','https://placehold.co/640x640/111827/f97316?text=EM','Spoken Word','Houston','Third Ward','{"instagram": "https://instagram.com/emancipation-echo", "tiktok": "https://tiktok.com/@emancipation-echo", "website": "https://example.com/emancipation-echo"}','{"spotify": "https://open.spotify.com/search/emancipation-echo", "youtube": "https://youtube.com/results?search_query=emancipation-echo", "soundcloud": "https://soundcloud.com/emancipation-echo", "bandcamp": "https://emancipation-echo.bandcamp.com"}',1,6,9);
INSERT OR IGNORE INTO songs (id,artist_id,title,slug,audio_url,downloadable_file_url,cover_art_url,is_download_enabled,download_count,stream_count,unique_listener_count,external_click_count,approved_at,is_approved) VALUES ('song-29','artist-29','Third Ward After Midnight','emancipation-echo-third-ward-after-midnight','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-14.mp3','https://placehold.co/640x640/0f172a/22d3ee?text=HI30',1,144,601,298,297,CURRENT_TIMESTAMP,1);
INSERT OR IGNORE INTO chart_entries (id,artist_id,rank,previous_rank,movement,score,week_start_date,week_end_date,is_manual_override) VALUES ('chart-29','artist-29',29,29,'same',3270,date('now','weekday 1','-7 days'),date('now','weekday 0'),0);
INSERT OR IGNORE INTO artists (id,name,slug,bio,image_url,genre,city,neighborhood,social_links,streaming_links,is_approved,editorial_score,local_relevance_score) VALUES ('artist-30','Airline Drive AM','airline-drive-am','A fictional Houston underground act channeling Northline block energy, DIY studio texture, and late-night Gulf Coast melodies.','https://placehold.co/640x640/111827/f97316?text=AI','Indie Folk','Houston','Northline','{"instagram": "https://instagram.com/airline-drive-am", "tiktok": "https://tiktok.com/@airline-drive-am", "website": "https://example.com/airline-drive-am"}','{"spotify": "https://open.spotify.com/search/airline-drive-am", "youtube": "https://youtube.com/results?search_query=airline-drive-am", "soundcloud": "https://soundcloud.com/airline-drive-am", "bandcamp": "https://airline-drive-am.bandcamp.com"}',1,10,8);
INSERT OR IGNORE INTO songs (id,artist_id,title,slug,audio_url,downloadable_file_url,cover_art_url,is_download_enabled,download_count,stream_count,unique_listener_count,external_click_count,approved_at,is_approved) VALUES ('song-30','artist-30','Loop 630 Lights','airline-drive-am-loop-630-lights','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3','https://www.soundhelix.com/examples/mp3/SoundHelix-Song-15.mp3','https://placehold.co/640x640/0f172a/22d3ee?text=HI30',1,140,570,280,290,CURRENT_TIMESTAMP,1);
INSERT OR IGNORE INTO chart_entries (id,artist_id,rank,previous_rank,movement,score,week_start_date,week_end_date,is_manual_override) VALUES ('chart-30','artist-30',30,29,'down',3149,date('now','weekday 1','-7 days'),date('now','weekday 0'),0);
INSERT OR IGNORE INTO users (id,email,password_hash,role) VALUES ('admin-1','admin@houstonindie30.local','demo-password-replace-with-auth-provider','admin');
INSERT OR IGNORE INTO rss_sources (id,name,url,category,is_active) VALUES ('source-1','Music Industry Wire','https://feeds.feedburner.com/musicbusinessworldwide','industry',1);
INSERT OR IGNORE INTO rss_sources (id,name,url,category,is_active) VALUES ('source-2','Houston Culture Desk','https://example.com/houston-music.rss','houston',1);
INSERT OR IGNORE INTO rss_sources (id,name,url,category,is_active) VALUES ('source-3','New Release Radar','https://example.com/new-releases.rss','releases',1);
INSERT OR IGNORE INTO rss_items (id,title,source,link,description,image_url,published_at,category) VALUES ('rss-1','Sample Houston Music Brief 1','Houston Indie 30 Seed','https://example.com/rss/1','Placeholder RSS summary for local music discovery. Replace with public RSS feed content during refresh.','https://placehold.co/900x520/111827/f97316?text=News',datetime('now','-1 days'),'houston');
INSERT OR IGNORE INTO rss_items (id,title,source,link,description,image_url,published_at,category) VALUES ('rss-2','Sample Industry Music Brief 2','Houston Indie 30 Seed','https://example.com/rss/2','Placeholder RSS summary for local music discovery. Replace with public RSS feed content during refresh.','https://placehold.co/900x520/111827/f97316?text=News',datetime('now','-2 days'),'industry');
INSERT OR IGNORE INTO rss_items (id,title,source,link,description,image_url,published_at,category) VALUES ('rss-3','Sample Releases Music Brief 3','Houston Indie 30 Seed','https://example.com/rss/3','Placeholder RSS summary for local music discovery. Replace with public RSS feed content during refresh.','https://placehold.co/900x520/111827/f97316?text=News',datetime('now','-3 days'),'releases');
INSERT OR IGNORE INTO rss_items (id,title,source,link,description,image_url,published_at,category) VALUES ('rss-4','Sample Houston Music Brief 4','Houston Indie 30 Seed','https://example.com/rss/4','Placeholder RSS summary for local music discovery. Replace with public RSS feed content during refresh.','https://placehold.co/900x520/111827/f97316?text=News',datetime('now','-4 days'),'houston');
INSERT OR IGNORE INTO rss_items (id,title,source,link,description,image_url,published_at,category) VALUES ('rss-5','Sample Industry Music Brief 5','Houston Indie 30 Seed','https://example.com/rss/5','Placeholder RSS summary for local music discovery. Replace with public RSS feed content during refresh.','https://placehold.co/900x520/111827/f97316?text=News',datetime('now','-5 days'),'industry');
