INSERT INTO workspaces (id, name, business_description, default_tone)
VALUES ('ws_1sv', '1 Soundvibe', 'Luxury Houston recording, podcast, membership, and event studio.', 'Street but respectful');

INSERT INTO team_members (id, workspace_id, name, email, role) VALUES
  ('tm_owner', 'ws_1sv', 'Jordan Owner', 'owner@1soundvibe.com', 'Owner'),
  ('tm_manager', 'ws_1sv', 'Nia Manager', 'manager@1soundvibe.com', 'Manager'),
  ('tm_va', 'ws_1sv', 'Sam VA', 'va@1soundvibe.com', 'VA'),
  ('tm_sales', 'ws_1sv', 'Ari Sales', 'sales@1soundvibe.com', 'Sales Rep');

INSERT INTO leads (id, workspace_id, name, username, profile_url, email, platform, source, tags, notes, status, city, profile_bio, last_contacted_at, assigned_member_id, consent_status) VALUES
  ('ld_001', 'ws_1sv', 'Maya Johnson', '@mayasingshtx', 'https://instagram.com/mayasingshtx', 'maya@example.com', 'Instagram', '#houstonartist', 'R&B,Houston,Warm', 'Asked about vocal chain and weekend availability.', 'Interested', 'Houston', 'R&B vocalist booking sessions and intimate live shows.', '2026-05-06', 'tm_sales', 'public_profile'),
  ('ld_002', 'ws_1sv', 'Corey Beatson', '@coreybeats', 'https://instagram.com/coreybeats', 'corey@example.com', 'Instagram', 'Competitor account commenters', 'Producer,Collab', 'Good fit for producer collaboration night.', 'Replied', 'Houston', 'Producer. Keys, drums, and sample flips.', '2026-05-07', 'tm_manager', 'public_profile'),
  ('ld_003', 'ws_1sv', 'Jalen Price', '@jalenpodcasts', 'https://instagram.com/jalenpodcasts', 'jalen@example.com', 'Instagram', 'Manual CSV import', 'Podcast,Booking', 'Imported from event list with consent to follow up.', 'New', 'Sugar Land', 'Host building a weekly founder interview show.', NULL, 'tm_va', 'uploaded_with_consent'),
  ('ld_004', 'ws_1sv', 'Tasha Monroe', '@tashamonroeofficial', 'https://instagram.com/tashamonroeofficial', NULL, 'Instagram', 'Vibe Check Thursday post commenters', 'Performer,Event', 'Booked a Thursday walkthrough.', 'Booked Tour', 'Houston', 'Singer-songwriter. Live set clips and studio diaries.', '2026-05-05', 'tm_sales', 'public_profile');

INSERT INTO campaigns (id, workspace_id, name, campaign_type, audience, message_step_1, follow_up_1, follow_up_2, wait_time_hours, stop_condition, daily_limit, is_running) VALUES
  ('cmp_001', 'ws_1sv', 'Houston recording studio tour', 'Studio tour invite', 'Houston artists and creators', 'Hey {first_name}, saw you through {source}. Your sound feels like it would fit the 1 Soundvibe rooms. Want me to send a quick studio tour link?', 'Just circling back, {first_name}. We have a few tour slots this week if you want to see the space before your next session.', 'No pressure — should I close the loop or keep you posted when tour times open up?', 72, 'Stop sequence immediately when the lead replies, opts out, or books.', 35, 1),
  ('cmp_002', 'ws_1sv', 'R&B artist session invite', 'Recording session offer', 'R&B singers and songwriters', 'Peace {first_name}, your vocals caught my attention. 1 Soundvibe has a clean setup for R&B sessions — want details on booking a session?', 'We can help with tracking, vocal production, and a comfortable room. Want me to send the booking link?', 'Last follow-up from me — if now is not the right time, I can check back later.', 72, 'Stop when the artist replies, declines, says stop, or books.', 25, 1),
  ('cmp_003', 'ws_1sv', 'Producer collaboration', 'Producer collaboration invite', 'Producers and beat makers', 'Yo {first_name}, I saw your producer work from {source}. We are connecting serious producers with artists at 1 Soundvibe — open to a collab intro?', 'Would a producer night or artist writing session be useful for you?', 'If you want, I can send the next invite when we lock the room schedule.', 96, 'Stop when the lead replies or opts out.', 20, 1),
  ('cmp_004', 'ws_1sv', 'Vibe Check Thursday invite', 'Vibe Check event invite', 'Performers and fans', 'Hey {first_name}, we host Vibe Check Thursday at 1 Soundvibe. Your energy looks like a fit — want the performer details?', 'Spots are limited and curated. Want me to send the signup link?', 'Should I keep you on the list for future Vibe Check dates?', 48, 'Stop when the lead replies, signs up, or declines.', 30, 1),
  ('cmp_005', 'ws_1sv', 'Podcast room booking', 'Podcast studio invite', 'Podcast hosts and video creators', 'Hey {first_name}, noticed your podcast work. 1 Soundvibe has a private podcast room if you ever need a clean recording setup — want the booking link?', 'We can support solo episodes, interviews, and short-form clips. Want to see times?', 'No worries if not — I can send details whenever you are ready.', 72, 'Stop when booked, replied, or opted out.', 25, 1),
  ('cmp_006', 'ws_1sv', 'Membership offer', 'Membership offer', 'Recurring creators', 'Hey {first_name}, if you are recording often, 1 Soundvibe memberships can make sessions simpler. Want the membership options?', 'Membership can help with room access, planning, and consistent creative workflow.', 'Should I send a quick breakdown or close this out?', 120, 'Stop when the lead replies, requests pricing, joins, or opts out.', 15, 1);
