import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";
import { slugify } from "../lib/utils";
import { defaultPlans, resourceTitles } from "../lib/content";
const prisma = new PrismaClient();
async function main() {
  const adminEmail = process.env.ADMIN_EMAIL ?? "admin@ccbnetwork.local";
  const adminPassword = process.env.ADMIN_PASSWORD ?? "ChangeMe123!";
  await prisma.user.upsert({ where:{email:adminEmail}, update:{}, create:{ name:"CCB Admin", email:adminEmail, role:"admin", passwordHash:await bcrypt.hash(adminPassword,12) } });
  const creators = await Promise.all(["Avery Brooks","Mia Carter","Jordan Ellis"].map(async (name,i)=>prisma.user.upsert({ where:{email:`creator${i+1}@ccbnetwork.local`}, update:{}, create:{ name, email:`creator${i+1}@ccbnetwork.local`, role:"creator", passwordHash:await bcrypt.hash("Creator123!",12), creatorProfile:{ create:{ fullName:name, organization:["Beacon House Media","Northstar Learning Lab","Indie Signal Films"][i], bio:"Fictional seed creator for the CCB Network MVP.", website:"https://example.com" } } } })));
  const categories = ["Faith & Ministry","Education","Indie Film","Wellness","Music","Community Business"];
  const networks = [];
  for (let i=0;i<6;i++) { const name = ["Beacon Streams","Northstar Academy TV","Indie Signal Channel","Whole Life Studio","Gold Note Sessions","Main Street Stories"][i]; const n = await prisma.network.upsert({ where:{slug:slugify(name)}, update:{}, create:{ ownerId:creators[i%3].id, name, slug:slugify(name), description:`${name} is a fictional CCB Network seed channel for web-first distribution demos.`, category:categories[i], targetAudience:"Niche communities seeking purposeful streaming content.", status:i%3===0?"distribution_ready":i%3===1?"live":"building", distributionGoals:"Web launch first, then evaluate connected-TV requirements.", monetizationGoals:"Sponsors, memberships, donations, and future subscriptions.", websiteUrl:"https://example.com", isApproved:true, isFeatured:i<3, distributionChecklist:{ create:{ hasBranding:true, hasContentLibrary:i<4, hasTrailer:i<3, hasRightsConfirmation:true, hasMonetizationPlan:i<5, hasAudienceStrategy:true, hasPrivacyPolicy:i<3, hasTerms:i<3, isReadyForReview:i<2 } } } }); networks.push(n); await prisma.show.upsert({ where:{slug:`${n.slug}-flagship`}, update:{}, create:{ networkId:n.id, title:`${name} Flagship`, slug:`${n.slug}-flagship`, description:"A fictional flagship show for seed data.", category:categories[i], isApproved:true } }); }
  for (let i=0;i<12;i++) await prisma.video.upsert({ where:{slug:`sample-episode-${i+1}`}, update:{}, create:{ networkId:networks[i%networks.length].id, title:`Sample Episode ${i+1}`, slug:`sample-episode-${i+1}`, description:"Original fictional seed video metadata for the CCB Network watch experience.", videoUrl:"https://www.youtube.com/watch?v=dQw4w9WgXcQ", duration:600+i*30, category:networks[i%networks.length].category, viewCount:i*17, isApproved:true, isFeatured:i<4 } });
  for (const [i,p] of defaultPlans.entries()) await prisma.pricingPlan.upsert({ where:{slug:slugify(p.name)}, update:{}, create:{...p, slug:slugify(p.name), sortOrder:i} });
  for (const title of resourceTitles) await prisma.resourceArticle.upsert({ where:{slug:slugify(title)}, update:{}, create:{ title, slug:slugify(title), excerpt:`A practical original CCB Network guide: ${title.toLowerCase()}.`, content:`<p>This original guide explains ${title.toLowerCase()} in a web-first launch model.</p><p>Start with audience, rights, workflow, cadence, and measurable goals before expanding to paid hosting or connected-TV apps.</p>`, category:"Launch Education", isPublished:true } });
  for (let i=0;i<10;i++) { await prisma.application.create({ data:{ fullName:`Applicant ${i+1}`, email:`applicant${i+1}@example.com`, organization:`Fictional Org ${i+1}`, networkName:`Future Network ${i+1}`, networkCategory:categories[i%categories.length], targetAudience:"Local and online communities", contentDescription:"A fictional application describing owned educational and inspirational video programming for launch review.", sampleVideoUrl:"https://www.youtube.com/watch?v=dQw4w9WgXcQ", monetizationGoals:"Sponsors and donations", distributionGoals:"Start web-first, prepare for TV apps later", budgetRange:i<3?"Free starter":"Builder", timeline:"30-90 days", rightsConfirmation:true, status:i%3===0?"approved":i%3===1?"pending":"rejected" } }); await prisma.lead.create({ data:{ name:`Lead ${i+1}`, email:`lead${i+1}@example.com`, source:"seed", interest:"Distribution planning", message:"Fictional lead for admin dashboard testing.", status:i%4===0?"qualified":i%4===1?"contacted":i%4===2?"new":"closed" } }); }
}
main().finally(()=>prisma.$disconnect());
