"use client";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { applicationSchema } from "@/lib/validation";
import { UploadField } from "./UploadField";
import type { z } from "zod";
type FormValues = z.infer<typeof applicationSchema>;
export function ApplicationForm() { const [state,setState] = useState<string>(); const { register, handleSubmit, formState:{ errors,isSubmitting }, reset } = useForm<FormValues>({ resolver: zodResolver(applicationSchema) });
  async function onSubmit(values: FormValues) { setState(undefined); const res = await fetch("/api/applications", { method:"POST", headers:{"content-type":"application/json"}, body: JSON.stringify(values) }); if (!res.ok) { setState("Please review your submission and try again."); return; } reset(); setState("Application received. CCB Network will review your web-first launch fit."); }
  const fields = [["fullName","Full name"],["email","Email"],["phone","Phone"],["organization","Organization or brand name"],["networkName","Network name"],["networkCategory","Network category"],["targetAudience","Target audience"],["currentPlatforms","Current platforms"],["websiteSocialLinks","Website/social links"],["sampleVideoUrl","Sample video link"],["monetizationGoals","Monetization goals"],["distributionGoals","Distribution goals"],["budgetRange","Budget range"],["timeline","Timeline"]] as const;
  return <form onSubmit={handleSubmit(onSubmit)} className="card grid gap-5"><input {...register("hp")} className="hidden" tabIndex={-1} autoComplete="off" />{fields.map(([name,label]) => <label key={name}><span className="label">{label}</span><input {...register(name)} className="input mt-2" />{errors[name] && <p className="mt-1 text-sm text-red-300">{errors[name]?.message as string}</p>}</label>)}<label><span className="label">Description of content</span><textarea {...register("contentDescription")} className="input mt-2 min-h-32" />{errors.contentDescription && <p className="mt-1 text-sm text-red-300">{errors.contentDescription.message}</p>}</label><UploadField name="sampleFile" label="Upload sample video (optional MVP placeholder)"/><label className="flex gap-3 rounded-2xl bg-white/5 p-4"><input type="checkbox" {...register("rightsConfirmation")} /><span>By submitting, you confirm that you own or control the rights to the content provided and authorize CCB Network to review it for potential distribution, hosting, or promotional opportunities.</span></label>{errors.rightsConfirmation && <p className="text-sm text-red-300">{errors.rightsConfirmation.message}</p>}<button disabled={isSubmitting} className="btn-primary">{isSubmitting ? "Submitting..." : "Submit Application"}</button>{state && <p className="rounded-2xl bg-white/10 p-4 text-sm text-gold">{state}</p>}</form>; }
