"use client";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { applicationSchema, contactSchema } from "@/lib/validation";
import type { z } from "zod";
export function UploadField({ name, label }: { name: string; label: string }) { return <label className="block"><span className="label">{label}</span><input name={name} type="file" accept="video/mp4,video/webm,image/png,image/jpeg,image/webp" className="input mt-2 file:mr-4 file:rounded-full file:border-0 file:bg-electric file:px-4 file:py-2 file:text-white"/><p className="mt-2 text-xs text-slate-500">Local MVP accepts MP4/WebM video and PNG/JPEG/WebP images.</p></label>; }
export function ApplicationForm() { const [state, setState] = useState<string>(); const { register, handleSubmit, formState: { errors, isSubmitting }, reset } = useForm<z.infer<typeof applicationSchema>>({ resolver: zodResolver(applicationSchema) }); async function onSubmit(values: z.infer<typeof applicationSchema>) { const res = await fetch("/api/applications", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(values) }); setState(res.ok ? "Application received. CCB Network will review your web-first launch fit." : "Please review your submission and try again."); if (res.ok) reset(); } const fields = [["fullName", "Full name"], ["email", "Email"], ["phone", "Phone"], ["organization", "Organization or brand name"], ["networkName", "Network name"], ["networkCategory", "Network category"], ["targetAudience", "Target audience"], ["currentPlatforms", "Current platforms"], ["websiteSocialLinks", "Website/social links"], ["sampleVideoUrl", "Sample video link"], ["monetizationGoals", "Monetization goals"], ["distributionGoals", "Distribution goals"], ["budgetRange", "Budget range"], ["timeline", "Timeline"]] as const; return <form onSubmit={handleSubmit(onSubmit)} className="card grid gap-5"><input {...register("hp")} className="hidden" tabIndex={-1}/>{fields.map(([name, label]) => <label key={name}><span className="label">{label}</span><input {...register(name)} className="input mt-2" />{errors[name] && <p className="mt-1 text-sm text-red-300">{errors[name]?.message as string}</p>}</label>)}<label><span className="label">Description of content</span><textarea {...register("contentDescription")} className="input mt-2 min-h-32" /></label><UploadField name="sampleFile" label="Upload sample video (optional MVP placeholder)"/><label className="flex gap-3 rounded-2xl bg-white/5 p-4"><input type="checkbox" {...register("rightsConfirmation")} /><span>By submitting, you confirm that you own or control the rights to the content provided and authorize CCB Network to review it for potential distribution, hosting, or promotional opportunities.</span></label><button disabled={isSubmitting} className="btn-primary">{isSubmitting ? "Submitting..." : "Submit Application"}</button>{state && <p className="rounded-2xl bg-white/10 p-4 text-sm text-gold">{state}</p>}</form>; }
export function ContactForm() { const [state, setState] = useState<string>(); const { register, handleSubmit, reset, formState: { isSubmitting } } = useForm<z.infer<typeof contactSchema>>({ resolver: zodResolver(contactSchema), defaultValues: { source: "contact" } }); async function onSubmit(values: z.infer<typeof contactSchema>) { const res = await fetch("/api/contact", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(values) }); setState(res.ok ? "Message received. We will follow up soon." : "Unable to send right now."); if (res.ok) reset(); } return <form onSubmit={handleSubmit(onSubmit)} className="card grid gap-5"><input {...register("hp")} className="hidden"/><label><span className="label">Name</span><input {...register("name")} className="input mt-2"/></label><label><span className="label">Email</span><input {...register("email")} className="input mt-2"/></label><label><span className="label">Reason for contact</span><input {...register("reason")} className="input mt-2"/></label><label><span className="label">Message</span><textarea {...register("message")} className="input mt-2 min-h-36"/></label><button disabled={isSubmitting} className="btn-primary">{isSubmitting ? "Sending..." : "Send Message"}</button>{state && <p className="rounded-2xl bg-white/10 p-4 text-gold">{state}</p>}</form>; }
